apiVersion: apps/v1
kind: Deployment
metadata:
  name: webflux-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webflux-app
  template:
    metadata:
      labels:
        app: webflux-app
    spec:
      containers:
      - name: webflux-app-container
        image: marciov/webfluximg:latest
        ports:
        - containerPort: 8080